### ISSUE TITLE
Issue submitting for license. 

### ISSUE THREAD

**Issue by orrzohar** [facebookresearch/Ego4d#308]
I filled in the form but when I try to submit, I get:

![image](https://github.com/facebookresearch/Ego4d/assets/108689663/87b795e6-48f9-4f28-8c13-e830f798c40c)

Best,
Orr

**Comment by phj128** [comment]
same issue.

**Comment by kimdoyun0208** [comment]
same issue.

**Comment by kylemin** [comment]
Same here

**Comment by orrzohar** [comment]
Hi Everyone,
The webside has been fixed.

**Comment by kylemin** [comment]
@orrzohar I'm still facing the issue. It says "Failed to fetch"
